version: "3"
services:
  backend:
    build:
      context: backend/.
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    tty: true
    stdin_open: true
    tmpfs:
      - /tmp
  redis:
    image: redis:3.2-alpine
    volumes:
      - "./redis-data:/data"
    ports:
      - "6379:6379"
