version: "3"
services:
  backend:
    build:
      context: backend/.
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
    tmpfs:
      - /tmp

  frontend:
    build:
      context: frontend/.
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    tmpfs:
      - /tmp
  redis:
    image: redis:3.2-alpine
    volumes:
      - "./redis-data:/data"
    ports:
      - "6379:6379"

  db:
    image: mariadb:10.6.1
    restart: always
    volumes:
      - "./mysql-db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: demo
    ports:
      - "3306:3306"

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
